version: "3.5"

# services / containers to start.
services:
  dev:
    image: debian-ssh:latest
    hostname: 'vipps-dev-1'
    restart: on-failure
    command: ["sleep","infinity"]
    networks:
        node_net:
          ipv4_address: 172.22.11.2

# networking for the Redis container
networks:
    node_net:
      ipam:
        driver: default
        config:
          - subnet: 172.22.11.0/24