version: "3.5"

# services / containers to start.
services:
  dev:
    image: debian-ssh:latest
    hostname: 'ansible-dev-1'
    restart: on-failure
    command: ["sleep","infinity"]
    networks:
        node_net:
          ipv4_address: 172.22.11.2

  test:
      image: debian-ssh:latest
      hostname: 'ansible-test-1'
      restart: on-failure
      command: ["sleep","infinity"]
      networks:
          node_net:
            ipv4_address: 172.22.11.3

  prod:
      image: debian-ssh:latest
      hostname: 'ansible-prod-1'
      restart: on-failure
      command: ["sleep","infinity"]
      networks:
          node_net:
            ipv4_address: 172.22.11.4

  frk:
      image: debian-ssh:latest
      hostname: 'ansible-frk-1'
      restart: on-failure
      command: ["sleep","infinity"]
      networks:
          node_net:
            ipv4_address: 172.22.11.11

  vie:
      image: debian-ssh:latest
      hostname: 'ansible-vie-1'
      restart: on-failure
      command: ["sleep","infinity"]
      networks:
          node_net:
            ipv4_address: 172.22.11.12

# networking for the Redis container
networks:
    node_net:
      ipam:
        driver: default
        config:
          - subnet: 172.22.11.0/24